[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_solana_learning = "8WPb8qwCTJzzSV5coCRditBzYrJCysDQSTJV25sbuJyo"

[programs.devnet]
anchor_solana_learning = "8WPb8qwCTJzzSV5coCRditBzYrJCysDQSTJV25sbuJyo"

[programs.mainnet]
anchor_solana_learning = "8WPb8qwCTJzzSV5coCRditBzYrJCysDQSTJV25sbuJyo"

[registry]
url = "https://api.apr.dev"                             # Anchor程序注册表的URL地址，本质上是一个程序包管理服务器

[provider]
cluster = "Devnet"                                      # 使用的网络环境(Localnet/Devnet/Mainnet)
wallet = "~/.config/solana/id.json"                     # 钱包密钥对文件路径

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
