[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
count_increment = "3QwVsMDRrF9hmQrgjFVDumXs5AHUtyy9VvQbwaJ9PF1t"
guess_random_number = "53huonbTydKqUQ6RSFgXXZGnc4HjFYAJHgWrabJpVLFj"
voting = "FhnUQ3mgYLTuLV7RZQaX4WMgnvigUoL4rKF8nH8PfqVc"

[programs.devnet]
count_increment = "3QwVsMDRrF9hmQrgjFVDumXs5AHUtyy9VvQbwaJ9PF1t"
guess_random_number = "53huonbTydKqUQ6RSFgXXZGnc4HjFYAJHgWrabJpVLFj"
voting = "FhnUQ3mgYLTuLV7RZQaX4WMgnvigUoL4rKF8nH8PfqVc"

[programs.mainnet]
count_increment = "3QwVsMDRrF9hmQrgjFVDumXs5AHUtyy9VvQbwaJ9PF1t"
guess_random_number = "53huonbTydKqUQ6RSFgXXZGnc4HjFYAJHgWrabJpVLFj"
voting = "FhnUQ3mgYLTuLV7RZQaX4WMgnvigUoL4rKF8nH8PfqVc"

[registry]
url = "https://api.apr.dev"                             # Anchor程序注册表的URL地址，本质上是一个程序包管理服务器

[provider]
cluster = "Devnet"                                      # 使用的网络环境(Localnet/Devnet/Mainnet)
wallet = "~/.config/solana/id.json"                     # 钱包密钥对文件路径

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
