[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
count_increment = "H5FMw8u5VcRq28jEujYZ4tQJgUxy94kUVBLvrAYHkecc"
curd_app = "6vnHJQpQL1G8x9DUTjAfsegeqwf2uPd56eNisEvnuoRn"
guess_random_number = "9MHvXBo6NCYGj1t6LvswH9PBqapAPj9jviyUJkQATt6d"
voting = "6ghmiYfqXdugFBdkMruXdhH6qD4rFoL1z7KeuxWeVEYo"
spl_token = "7VE1KT8XXssnwBcYA3eZbmi4ZCkVPWzQZam63ZDQfQQn"


[programs.devnet]
count_increment = "H5FMw8u5VcRq28jEujYZ4tQJgUxy94kUVBLvrAYHkecc"
curd_app = "6vnHJQpQL1G8x9DUTjAfsegeqwf2uPd56eNisEvnuoRn"
guess_random_number = "9MHvXBo6NCYGj1t6LvswH9PBqapAPj9jviyUJkQATt6d"
voting = "6ghmiYfqXdugFBdkMruXdhH6qD4rFoL1z7KeuxWeVEYo"
spl_token = "7VE1KT8XXssnwBcYA3eZbmi4ZCkVPWzQZam63ZDQfQQn"

[programs.mainnet]
count_increment = "H5FMw8u5VcRq28jEujYZ4tQJgUxy94kUVBLvrAYHkecc"
curd_app = "6vnHJQpQL1G8x9DUTjAfsegeqwf2uPd56eNisEvnuoRn"
guess_random_number = "9MHvXBo6NCYGj1t6LvswH9PBqapAPj9jviyUJkQATt6d"
voting = "6ghmiYfqXdugFBdkMruXdhH6qD4rFoL1z7KeuxWeVEYo"
spl_token = "7VE1KT8XXssnwBcYA3eZbmi4ZCkVPWzQZam63ZDQfQQn"

[registry]
url = "https://api.apr.dev"                             # Anchor程序注册表的URL地址，本质上是一个程序包管理服务器

[provider]
cluster = "Localnet"                                    # 使用的网络环境(Localnet/Devnet/Mainnet)
# cluster = "Devnet"                                    # 使用的网络环境(Localnet/Devnet/Mainnet)
# cluster = "Mainnet"                                   # 使用的网络环境(Localnet/Devnet/Mainnet)

# cluster = "https://young-restless-bridge.solana-devnet.quiknode.pro/64df14141046ed00f4320d627db7e1119aef0b52"       # 指定 RPC
wallet = "~/.config/solana/id.json"                                                                                 # 钱包密钥对文件路径

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
